services:
  database:
    container_name: 'intermin_db'
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'inter_user'
      POSTGRES_PASSWORD: 'inter_password'
      POSTGRES_DB: 'intermin_db'
    ports:
      - '5432:5432'
    volumes:
      - inter-sql-volume:/applis/docker-compose/inter-sql/data

volumes:
  inter-sql-volume:

networks:
  backNetWork:
    driver: bridge